name: Trigger Jenkins Build
on: [push]
env:
  JENKINS_HOST: "http://35.232.120.3:8080/"
  JENKINS_JOB: "job/test/"
jobs:
  trigger:
    name: Triggering Jenkins Build
    runs-on: ubuntu-18.04
    steps:
      - name: Triggering Jenkins Build
        uses: GoldenspearLLC/build-jenkins-job@master
        with:
          jenkins-url: ${{ env.JENKINS_HOST }}
          user: ${{ secrets.JENKINS_USER }}
          jenkins-token: ${{ secrets.TOKEN }}
          job-path: ${{ env.JENKINS_JOB }}
          job-params: "{'FRESH_BUILD':'True', 'BUILD_BRANCH':'main', 'DEPLOY_DEV':'True', 'DEPLOY_QA':'False, 'DEPLOY_STAGING':'False, 'DEPLOY_PRODUCTION':'False'}"
