name: Trigger Jenkins Build
on:
  pull_request:
    branches: [master]
    types: [closed]
env:
  JENKINS_HOST: "http://35.232.120.3:8080/"
  JENKINS_JOB: "job/test/"
jobs:
  trigger:
    name: Triggering Jenkins Build
    runs-on: ubuntu-latest
    steps:
      - name: Triggering Jenkins Build
        uses: GoldenspearLLC/build-jenkins-job@master
        with:
          jenkins-url: ${{ env.JENKINS_HOST }}
          user: ${{ secrets.JENKINS_USER }}
          jenkins-token: ${{ secrets.TOKEN }}
          job-path: ${{ env.JENKINS_JOB }}
