name: CI

on:
  pull_request:
    branches:
      - test/*
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: trigger single Job
        uses: appleboy/jenkins-action@master
        with:
          url: "http://35.232.120.3:8080/"
          user: "shivam_purohit"
          token: ${{ secrets.TOKEN }}
          job: "test"
