name: Test Jenkins Action

on: [push, pull_request]

jobs:
  testaction:
    runs-on: ubuntu-latest

    steps:
      - id: testjenkinsaction
        uses: mickeygoussetorg/trigger-jenkins-job@v1
        with:
          jenkins-server: http://35.232.120.3:8080/ # URL of the jenkins server
          jenkins-job: test # The name of the jenkins job to run
          jenkins-username: shivam_purohit # user name for accessing jenkins
          jenkins-pat: ${{ secrets.GithubActionsToken }} # personal Access token for accessing Jenkins
          # poll-time: # how often (in seconds) to poll the jenkins server for results
          # timeout-value: # How long (in seconds) to poll before timing out the action
          verbose: true # true/false - turns on extra logging
