name: trigger jenkins job
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: trigger single Job
        uses: appleboy/jenkins-action@master
        with:
          url: "http://35.232.120.3:8080/"
          user: "example"
          token: ${{ secrets.TOKEN }}
          job: "test"
